# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HandFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHandFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HandFrameBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x48\x41\x4E\x44", size_prefixed=size_prefixed)

    # HandFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandFrame
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HandFrame
    def HandType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HandFrame
    def Joints(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from VIRTOSHA.FlatBuffers.Joint import Joint
            obj = Joint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HandFrame
    def JointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HandFrame
    def JointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def HandFrameStart(builder):
    builder.StartObject(3)

def Start(builder):
    HandFrameStart(builder)

def HandFrameAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    HandFrameAddTimestamp(builder, timestamp)

def HandFrameAddHandType(builder, handType):
    builder.PrependUint8Slot(1, handType, 0)

def AddHandType(builder, handType):
    HandFrameAddHandType(builder, handType)

def HandFrameAddJoints(builder, joints):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(joints), 0)

def AddJoints(builder, joints):
    HandFrameAddJoints(builder, joints)

def HandFrameStartJointsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJointsVector(builder, numElems):
    return HandFrameStartJointsVector(builder, numElems)

def HandFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return HandFrameEnd(builder)
