# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Joint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Joint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def JointBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x48\x41\x4E\x44", size_prefixed=size_prefixed)

    # Joint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Joint
    def JointIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Joint
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from VIRTOSHA.FlatBuffers.Vec3 import Vec3
            obj = Vec3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Joint
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from VIRTOSHA.FlatBuffers.Quat import Quat
            obj = Quat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def JointStart(builder):
    builder.StartObject(3)

def Start(builder):
    JointStart(builder)

def JointAddJointIndex(builder, jointIndex):
    builder.PrependUint8Slot(0, jointIndex, 0)

def AddJointIndex(builder, jointIndex):
    JointAddJointIndex(builder, jointIndex)

def JointAddPosition(builder, position):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)

def AddPosition(builder, position):
    JointAddPosition(builder, position)

def JointAddRotation(builder, rotation):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rotation), 0)

def AddRotation(builder, rotation):
    JointAddRotation(builder, rotation)

def JointEnd(builder):
    return builder.EndObject()

def End(builder):
    return JointEnd(builder)
